### ISSUE TITLE
Vault with the Mongo free tier cluster issue

### ISSUE THREAD

**Issue by SaintAngeLs** [SaintAngeLs/courier_app#1]
in case of running the Vault with the mongo tier on the free tier, it is impossible to avoid the next issue

````
(kaliuser㉿kali)-[~/…/courierapp/courier_app/SwifttParcel.Services.Identity/scripts]`
└─$ ./start.sh                   
Building...
Loading settings from Vault: 'http://127.0.0.1:8200', KV path: 'identity-service/settings'.
Initializing Vault lease for: 'mongo', type: 'database'.
Unhandled exception. VaultSharp.Core.VaultApiException: {"errors":["1 error occurred:\n\t* (AtlasError) CMD_NOT_ALLOWED: createUser\n\n"]}

   at VaultSharp.Core.Polymath.MakeRequestAsync[TResponse](String resourcePath, HttpMethod httpMethod, Object requestData, IDictionary`2 headers, Boolean rawResponse, Action`1 postResponseAction)
   at VaultSharp.Core.Polymath.MakeVaultApiRequest[TResponse](String resourcePath, HttpMethod httpMethod, Object requestData, Boolean rawResponse, Action`1 postResponseAction, String wrapTimeToLive, Boolean unauthenticated)
   at VaultSharp.Core.Polymath.MakeVaultApiRequest[TResponse](String mountPoint, String path, HttpMethod httpMethod, Object requestData, Boolean rawResponse, Action`1 postResponseAction, String wrapTimeToLive, Boolean unauthenticated)
   at VaultSharp.V1.SecretsEngines.Database.DatabaseSecretsEngineProvider.GetCredentialsAsync(String roleName, String mountPoint, String wrapTimeToLive)
   at Convey.Secrets.Vault.Extensions.SetDatabaseSecretsAsync(String key, IVaultClient client, LeaseOptions options, IDictionary`2 configuration)
   at Convey.Secrets.Vault.Extensions.AddVaultAsync(IConfigurationBuilder builder, VaultOptions options, String keyValuePath)
   at Convey.Secrets.Vault.Extensions.<>c__DisplayClass4_0.<UseVault>b__1(WebHostBuilderContext ctx, IConfigurationBuilder cfg)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at src.SwiftParcel.Services.Identity.Api.Program.Main(String[] args) in /home/kaliuser/Documents/portfolio/commercial_apps/courierapp/courier_app/SwifttParcel.Services.Identity/src/SwiftParcel.Services.Identity.Api/SwiftParcel.Services.Identity.Api/Program.cs:line 23
   at src.SwiftParcel.Services.Identity.Api.Program.<Main>(String[] args)
```


The all hope we have, we will intensively and disparately put on the Mr. Marcin back

**Comment by SaintAngeLs** [comment]
This issue was resolved with the vault settings update
