### ISSUE TITLE
MessageBrocker issue

### ISSUE THREAD

**Issue by SaintAngeLs** [SaintAngeLs/courier_app#5]
Resolve the issue by class MaessageBrocker and the IMessageBroker interface modification, as the issue is:
```bash
[18:57:46 INF] Request starting HTTP/1.1 POST http://localhost:6001/sign-up application/json 65
[18:57:46 INF] CORS policy execution successful.
[18:57:46 INF] Executing endpoint 'sign-up HTTP: POST'
[18:57:47 INF] Created an account for the user with id: 9ea36bc1-dedc-4936-9c4d-183d90d48b78.
[18:57:47 INF] Executed endpoint 'sign-up HTTP: POST'
[18:57:47 ERR] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at SwiftParcel.Services.Identity.Infrastructure.MessageBrokers.MessageBroker.PublishAsync[T](T event) in /home/kaliuser/Documents/portfolio/commercial_apps/courierapp/courier_app/SwifttParcel.Services.Identity/src/SwiftParcel.Services.Identity.Infrastructure/SwiftParcel.Services.Identity.Infrastructure/MessageBrokers/MessageBroker.cs:line 21
   at SwiftParcel.Services.Identity.Identity.Application.Services.IdentityService.SignUpAsync(SignUp command) in /home/kaliuser/Documents/portfolio/commercial_apps/courierapp/courier_app/SwifttParcel.Services.Identity/src/SwiftParcel.Services.Identity.Application/SwiftParcel.Services.Identity.Application/Services/IdentityService.cs:line 118
   at src.SwiftParcel.Services.Identity.Api.Program.<>c.<<Main>b__0_9>d.MoveNext() in /home/kaliuser/Documents/portfolio/commercial_apps/courierapp/courier_app/SwifttParcel.Services.Identity/src/SwiftParcel.Services.Identity.Api/SwiftParcel.Services.Identity.Api/Program.cs:line 63
--- End of stack trace from previous location ---
   at Convey.WebApi.EndpointsBuilder.BuildRequestContext[T](HttpContext httpContext, Func`3 context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Convey.Auth.AccessTokenValidatorMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Convey.WebApi.Exceptions.ErrorHandlerMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
[18:57:48 INF] Request finished HTTP/1.1 POST http://localhost:6001/sign-up application/json 65 - 400 - application/json 1217.4649ms
^CApplication is shutting down...
[19:05:12 INF] Deregistering a servi

```

**Comment by SaintAngeLs** [comment]
The issue was resolved in the specifically sophisticated urgent matter
