### ISSUE TITLE
Identity service

### ISSUE THREAD

**Issue by SaintAngeLs** [SaintAngeLs/courier_app#77]
in case of signing in identity service throws the error:

```bash
[01:04:07 INF] Executing endpoint 'sign-in HTTP: POST'
[01:04:07 ERR] User with email: courier@email.com was not found.
[01:04:07 INF] Executed endpoint 'sign-in HTTP: POST'
[01:04:07 ERR] Invalid credentials.
SwiftParcel.Services.Identity.Core.Exceptions.InvalidCredentialsException: Invalid credentials.
   at SwiftParcel.Services.Identity.Identity.Application.Services.IdentityService.SignInAsync(SignIn command) in /home/kaliuser/Documents/portfolio/commercial_apps/courierapp/courier_app/SwifttParcel.Services.Identity/src/SwiftParcel.Services.Identity.Application/SwiftParcel.Services.Identity.Application/Services/IdentityService.cs:line 74
   at src.SwiftParcel.Services.Identity.Api.Program.<>c.<<Main>b__0_6>d.MoveNext() in /home/kaliuser/Documents/portfolio/commercial_apps/courierapp/courier_app/SwifttParcel.Services.Identity/src/SwiftParcel.Services.Identity.Api/SwiftParcel.Services.Identity.Api/Program.cs:line 59
--- End of stack trace from previous location ---
   at Convey.WebApi.EndpointsBuilder.BuildRequestContext[T](HttpContext httpContext, Func`3 context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Convey.Auth.AccessTokenValidatorMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Convey.WebApi.Exceptions.ErrorHandlerMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
[01:04:07 INF] Request finished HTTP/1.1 POST http://localhost:5004/sign-in application/json 60 - 400 - application/json 130.0434ms



```

**Comment by SaintAngeLs** [comment]
This issue is resolved bu #78
